
development:
  adapter: mysql2
  database: msc_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: msc_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: msc_production
  username: root
  password: 
  encoding: utf8
